### ISSUE TITLE
Upgrade OAuth 2 for Sina Weibo (Or all services ?)

### ISSUE THREAD

**Issue by icyleaf** [icyleaf/ShareKit#2]
Here has two solution below:
1. Migrating to OAuth 2 (Good for almost support OAuth2 services)
2. Using [Sina Weibo OAuth 1 & 2 bridge api](http://open.weibo.com/wiki/Oauth2/get_oauth2_token) (Using OAuth1 acess token exchange Oauth2 access token & expires timestamp)

**Comment by YoniTsafir** [comment]
+1

**Comment by icyleaf** [comment]
Completed with commit SHA: a16b8a19a44c0c2b90eb6879e83c66ab0d2c5960 & SHA: 5352dee18950b36d3993a8e5d65607e17a1abd61

Here is import sina weibo official sdk: [weibo_ios_sdk_sso-oauth](https://github.com/mobileresearch/weibo_ios_sdk_sso-oauth), and iOS 6 Social framework (issue #4).

Flow:
1. Check iOS version, if it is ios 6, then continue check social type (sinaweibo must chinese language), all pass, it calls Social panel.
2. Check Sina Weibo app is installed,  then open the app (likes Facebook app auth flow).
3. None of above, open url built-in UIWebView.

**Comment by icyleaf** [comment]
Only upgrade for Sina weibo to support OAuth 2
