### ISSUE TITLE
豆瓣、新浪、腾讯、人人等中文的分享功能全部不见了。

### ISSUE THREAD

**Issue by tobytaro** [icyleaf/ShareKit#3]
我最近用submodule的方式更新了您开发的最新版sharekit，一切都很顺利，但是分享的时候，所有中文服务都不在分享菜单里面，包括新浪、腾讯、豆瓣等等，其他国外的facebook，twitter等则可以正常使用。
请问是什么原因，我检查了SHKSharer.plist也都列上去了。以前版本使用的时候完全没有这个问题。我除了submodule更新之外没有对sharekit文件做任何调整，MySHKConfigurator文件也没有做过改动。
为什么出现这种情况，请指教，谢谢！

**Comment by icyleaf** [comment]
你用的是哪个分支的代码？

**Comment by tobytaro** [comment]
我用的是develop分支，我查询了代码，sina、人人、网易、腾讯等都有相应的文件夹和代码。但是就是不知道怎么回事使用的时候显示不出来。

**Comment by icyleaf** [comment]
你尝试根据 ShareKitDemoConfigurator.h/m 的文件重新配置下。刚才又更新了下代码，现在已经合并了最新的 ShareKit/ShareKit 代码，本地尝试没有问题。

BTW，新浪微博目前还是支持 OAuth 1，应该是无法使用 :)

**Comment by tobytaro** [comment]
问题已经解决，谢谢。是我在更新submodules时操作问题。现在中文微博除了sina，其他都正常。但是evernote 和 tumblr 不可用，不知道什么原因，是不是他们更新了api接口？

**Comment by icyleaf** [comment]
evernote 和 tumblr 我没有进行测试，不过今天的代码 flickr 和 flickr sdk 没有同步，出现了一些问题。

**Comment by icyleaf** [comment]
1. [_official_ Tumblr v1 API no longer functions. Read-only](https://github.com/ShareKit/ShareKit/issues/503)
2. [Crash when I use Evernote](https://github.com/ShareKit/ShareKit/issues/548)
