### ISSUE TITLE
更新最新的版本后出现编译错误。

### ISSUE THREAD

**Issue by tobytaro** [icyleaf/ShareKit#5]
提示如下：请问是什么问题？

Undefined symbols for architecture armv7:
  "_SLServiceTypeSinaWeibo", referenced from:
      -[SHKiOS6SinaWeibo presentUI] in libShareKit.a(SHKiOS6SinaWeibo.o)
      -[SHKSinaWeibo socialFrameworkAvailable] in libShareKit.a(SHKSinaWeibo.o)
  "_OBJC_CLASS_$_SLComposeViewController", referenced from:
      objc-class-ref in libShareKit.a(SHKiOS6SinaWeibo.o)
      objc-class-ref in libShareKit.a(SHKSinaWeibo.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

 "_SLServiceTypeSinaWeibo", referenced from:

```
  -[SHKiOS6SinaWeibo presentUI] in libShareKit.a(SHKiOS6SinaWeibo.o)


  -[SHKSinaWeibo socialFrameworkAvailable] in libShareKit.a(SHKSinaWeibo.o)
```

  "_OBJC_CLASS_$_SLComposeViewController", referenced from:

```
  objc-class-ref in libShareKit.a(SHKiOS6SinaWeibo.o)


  objc-class-ref in libShareKit.a(SHKSinaWeibo.o)
```

ld: symbol(s) not found for architecture armv7

clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by tobytaro** [comment]
更新的时候，先是提示我
error: Your local changes to the following files would be overwritten by merge:
    ShareKit.xcodeproj/project.pbxproj
Please, commit your changes or stash them before you can merge.
后来我就用了
git reset --hard
git pull
之后貌似很顺利地更新了。
会不会我操作错误？

**Comment by icyleaf** [comment]
Do you update all submodules? try this:

```
$ git submodule update --init
```

To be sure, u r using ShareKit 2.0.

**Comment by tobytaro** [comment]
Now I find the solution.
Just add social.framework to my project.

**Comment by icyleaf** [comment]
And set it 'optional'
