### ISSUE TITLE
請問這是甚麼地方出錯? 謝謝!

### ISSUE THREAD

**Issue by zeropt7** [icyleaf/ShareKit#6]
**\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[SHKOAuthView navigationBar]: unrecognized selector sent to instance 0x1d01afe0'

**Comment by icyleaf** [comment]
请问你都设置了什么操作？

**Comment by icyleaf** [comment]
暂时关闭，如果还有疑问，请重新开启。
